# Generated by Django 3.0.3 on 2020-10-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='flag',
            field=models.CharField(blank=True, choices=[('racist', 'racist'), ('abusing', 'abusing')], max_length=20, null=True),
        ),
    ]
